version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: app
    expose:
      - 3333
    ports:
      - 3333:3333
    command: ['pnpm', 'dev']
